import Random from "random"

let rng1 = Random.make(0xf00L)
let rng2 = Random.make(0xf00L)

assert Random.nextInt32(rng1) == 833494444l
assert Random.nextInt32(rng2) == 833494444l
assert Random.nextInt32(rng1) == -1746193004l
assert Random.nextInt32(rng2) == -1746193004l

assert Random.nextInt32(rng1) == Random.nextInt32(rng2)
assert Random.nextInt64(rng1) == Random.nextInt64(rng2)
assert Random.nextInt64(rng1) == Random.nextInt64(rng2)

assert Random.nextInt64(rng1) == -2063148927841070477L
assert Random.nextInt64(rng2) == -2063148927841070477L
assert Random.nextInt64(rng1) != -2063148927841070477L
